### ISSUE TITLE
does not work with mkdocs >=1.6.0

### ISSUE THREAD

**Issue by danaukes** [Tiryoh/actions-mkdocs#230]
Hi there - 
Thanks for the great tool.  I have encountered a recent issue where the workflow no longer works with mkdocs v 1.6.0 or greater.  Previously (beginning of may) I was able to specify the following in my .github/workflows/pages.yml config:

```yaml
...
jobs:
  build:
    name: build mkdocs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Build
      uses: Tiryoh/actions-mkdocs@v0
      with:
        mkdocs_version: '1.6.1' # option
        requirements: 'requirements.txt' # option
        configfile: 'mkdocs.yml' # option
...
```

The requirements.txt file looked like this:

```
mkdocs-get-deps==0.2.0
mkdocs-glightbox==0.4.0
mkdocs-material==9.5.36           
mkdocs-material-extensions==1.3.1
mkdocs-rss-plugin==1.15.0
```

It ran fine.  Now, however, when I build, the action shows uninstalling and reinstalling the desired packages (showing up to mkdocs-material)

```
...
Installing collected packages: mkdocs-glightbox, msgpack, mkdocs-get-deps, filelock, cachecontrol, mkdocs, mkdocs-rss-plugin, mkdocs-material
  Attempting uninstall: mkdocs
    Found existing installation: mkdocs 1.5.3
    Uninstalling mkdocs-1.5.3:
      Successfully uninstalled mkdocs-1.5.3
  Attempting uninstall: mkdocs-material
    Found existing installation: mkdocs-material 9.5.18
    Uninstalling mkdocs-material-9.5.18:
      Successfully uninstalled mkdocs-material-9.5.18
Successfully installed cachecontrol-0.14.3 filelock-3.18.0 mkdocs-1.6.1 mkdocs-get-deps-0.2.0 mkdocs-glightbox-0.4.0 mkdocs-material-9.5.36 mkdocs-rss-plugin-1.15.0 msgpack-1.1.1
...
```

But despite this, it causes an error:

```
Because mkdocs-actions depends on mkdocs-material (9.5.18) which depends on mkdocs (>=1.5.3,<1.6.0), mkdocs is required.
So, because mkdocs-actions depends on mkdocs (1.6.1), version solving failed.
```

I have tried updating requirements, reverting requirements, including pip>=24 in my requirements, requiring mkdocs>=1.6.0 in my requirements.txt, but the only thing that works now is to remove the mkdocs and mkdocs-material package version requirements.

How can I take advantage of the most up-to-date version while avoiding this new issue?

Thanks!
