### ISSUE TITLE
Multi-level navigation tree issue with GH actions only 

### ISSUE THREAD

**Issue by JostTim** [Tiryoh/actions-mkdocs#63]
Hi there,
Thanks for your work, seems to work great, and is well documented, I could make it work easily even though i never had setup any github action workflow before.
There is a little issue that i wish to report though.

When ``mkdocs serve``-ing locally my site or deploying it manually, i have no issue with any page.
Howerver, when deployed automatically after a push on main, any page that is existing under a subfolder is linked to an adress finishing by .md instead of .html and thus gives a 404 error.

This is the nav configuration for my ``mkdocs.yml`` file :

````yml
nav:
    - Home: index.md
    
    - Topic: 
        - 'Stuff': 'folder/stuff.md'
        - 'Another Thing': 'folder/another_thing.md'
        
    - Notes: 'Notes.md'
     
    - Concepts :
        - 'Mathematics': 'Mathematics.md'
        - 'Statistics' : 'Statistics.md'
        - 'Physics': 'Physics.md'
        - 'Optics': 'Optic.md'
        - 'Biology': 'Biology.md'
 ````

All pages are "linked" correctly except for the ones that are present inside subfolders. So the ones under  ``Topic`` here. 
Do you know if it's because you don't support yet that kind of architecture or if it's because i messed up with something in my 
``github-actions.yml`` file ?

Here it is by the way : 
````yml
name: Deploy
on: push

jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          #mkdocs_version: '1.1' # option
          requirements: 'requirements.txt' # option
          configfile: 'mkdocs.yml' # option
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
````
